### ISSUE TITLE
Errors when i'm trying to run the app

### ISSUE THREAD

**Issue by FellipeG** [lvs-coding/LVS.Training.Android.Lab.EbookBilingualReader#1]
when i'm trying to run the app it forced closes.

logcat:

06-27 00:13:15.434 11329-11329/com.example.bilingualbookreader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.example.bilingualbookreader, PID: 11329
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bilingualbookreader/com.example.bilingualbookreader.activities.DualBookActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:153)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6240)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                                  Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                                                  Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class fragment
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
                                                                                     at com.example.bilingualbookreader.helpers.BookHelper.openBook(BookHelper.java:86)
                                                                                     at com.example.bilingualbookreader.fragments.MainBookFragment.onCreateView(MainBookFragment.java:31)
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1254)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
                                                                                     at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1681)
                                                                                     at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3357)
                                                                                     at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                                     at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
                                                                                     at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                                     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                     at com.example.bilingualbookreader.activities.DualBookActivity.onCreate(DualBookActivity.java:18)
                                                                                     at android.app.Activity.performCreate(Activity.java:6684)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:153)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6240)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

PS: I didn't modify anything.

**Comment by lvs-coding** [comment]
It's "normal" this is still in progress......

**Comment by FellipeG** [comment]
Ok, thanks for your response!
